### ISSUE TITLE
Something wrong in Demo?

### ISSUE THREAD

**Issue by Techhooli** [zju3dv/NeuralRecon#10]
First of all, thank you for your code. I look forward to use it, But now I come across some errors. I follows your step in Demo. Can you tell me how to solve it?

Traceback (most recent call last):
  File "demo.py", line 91, in <module>
    save_mesh_scene.save_scene_eval(epoch_idx, outputs)
  File "/data/g00577352/NeuralRecon/utils.py", line 270, in save_scene_eval
    tsdf_volume = outputs['scene_tsdf'][0].data.cpu().numpy()
KeyError: 'scene_tsdf'

**Comment by JiamingSuen** [comment]
Thanks for your interest in our work. This error indicates that the reconstruction is failed. Which data are you using? Can you run the demo smoothly with the demo data?

**Comment by Techhooli** [comment]
Thank you for your ripid response. I am testing the example data which you provided.  And I only modify the data path in demo.yaml. The error appears:

 99%|██████████████████████████████████████████████████████████████▍| 109/110 [01:24<00:00,  1.29it/s]
Traceback (most recent call last):
  File "demo.py", line 91, in <module>
    save_mesh_scene.save_scene_eval(epoch_idx, outputs)
  File "/data/g00577352/NeuralRecon/utils.py", line 270, in save_scene_eval
    tsdf_volume = outputs['scene_tsdf'][0].data.cpu().numpy()
KeyError: 'scene_tsdf'
I think it's very strange.

However, when I set REDUCE_GPU_MEM false or set VIS_INCREMENTAL true. The program can work well. And the screen shows
Summary:
    Total number of fragments: 110
    Average keyframes/sec: 14.899766978859263
    Average GPU memory usage (GB): 0.7904296875
    Max GPU memory usage (GB): 1.25
Moreover, when I set VIS_INCREMENTAL true, only the window of selected keyframes is shown? So the dynamic reconstruction window in the website is post-processed? I dont known if I have gone through your code sucessfully.

**Comment by JiamingSuen** [comment]
Hi @Techhooli, this is a regression and is already fixed in #11. Feel free to reopen this issue if you have more questions.
