### ISSUE TITLE
**THE problem about ios_logger's complie?**

### ISSUE THREAD

**Issue by LLKLLK1** [zju3dv/NeuralRecon#107]
Hi Team, thanks for sharing this outstanding piece of work. When I run iOS_Logger.app, I encounter a problem with the following message:
assetWriter: Error Domain=AVFoundationErrorDomain
Code = -11834"Cannot Encode"
UserInfo  = {AVErrorMediaSubTypekey=(1752589105)
,NSLocalizedFailureReason = The encoder required for this
media cannot be found.,AVErrorMediaTypeKey=vide,
NSLocalizedDescription=Cannot Encode
}
I wonder how I should solve this problem？Can you help me ？ I'm very interested in your results。

- l am looking farword to you reply!

**Comment by LLKLLK1** [comment]
![IMG_20220727_114649](https://user-images.githubusercontent.com/61173033/181157011-13a1db96-ded4-416b-989e-1166beaa4e0f.jpg)
![IMG_20220727_114836](https://user-images.githubusercontent.com/61173033/181157059-10b2e2e5-2ccf-48c8-b804-2410cb77e9b1.jpg)
![QQ图片20220727035037](https://user-images.githubusercontent.com/61173033/181157064-84eaa3af-19bb-4396-9626-67e9dc0af882.jpg)

**Comment by berkcetinsaya** [comment]
Hi @LLKLLK1 ,

I believe your issue is about the ios_logger app, not the NeuralRecon. You should open an issue on their [GitHub page](https://github.com/Varvrar/ios_logger) to find out what is wrong with the version you use.

Best,
