### ISSUE TITLE
KeyError: 'scene_tsdf'

### ISSUE THREAD

**Issue by Vadkoz** [zju3dv/NeuralRecon#14]
This bug should have been fixed by one of the last commits but still occurs on some of my own data (not all videos). 

  batch_ind = torch.nonzero(coords[:, 0] == batch).squeeze(1)
  6%|███▍                                                        | 11/191 [00:03<00:41,  4.35it/s]2021-05-27 09:33:50.236 | WARNING  | models.neucon_network:forward:184 - no valid points: scale 2
  6%|███▍                                                        | 11/191 [00:03<00:53,  3.35it/s]
Traceback (most recent call last):
  File "demo.py", line 81, in <module>
    save_mesh_scene(outputs, sample, epoch_idx)
  File "NeuralRecon/utils.py", line 322, in __call__
    self.tsdf_volume[3] = outputs['scene_tsdf']
KeyError: 'scene_tsdf'

Maybe the reason is the wrong video filming? Can you describe how to make a video with the maximum number of relevant frames?

**Comment by JiamingSuen** [comment]
We've added some info for this error.
https://github.com/zju3dv/NeuralRecon/blob/1234241542fed949b8b632d64914fa417f018d16/demo.py#L95-L100

This message indicates that the reconstruction is failed. If you are experiencing this error only on one or two sequences, the reason could be that these sequences are extremely hard and no voxel has been predicted by the network to have an occupancy larger than the threshold. This error rarely appears in our own experiments and we recommend you upload the captured data for us to further determine the difficulty of the data.

**Comment by JiamingSuen** [comment]
Closed due to inactivity. Feel free to reopen this issue if you would like to continue the conversation. @Vadkoz

**Comment by ynma-hanvo** [comment]
> We've added some info for this error.
> 
> https://github.com/zju3dv/NeuralRecon/blob/1234241542fed949b8b632d64914fa417f018d16/demo.py#L95-L100
> 
> This message indicates that the reconstruction is failed. If you are experiencing this error only on one or two sequences, the reason could be that these sequences are extremely hard and no voxel has been predicted by the network to have an occupancy larger than the threshold. This error rarely appears in our own experiments and we recommend you upload the captured data for us to further determine the difficulty of the data.

i am also fail with this issue for my own data.   
i check the issue list that some people say need to apply a transformation to my own pose which is generated by some vo framework.      but i never succeeded on any   transformation.  
by the way , when i adjust  N_VOX  to bigger , i got some mesh although it is quite sparse also.
  is there any special requirements for the data capture.
