### ISSUE TITLE
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe 

### ISSUE THREAD

**Issue by Cyberyyc** [zju3dv/NeuralRecon#147]
The project‘s dependecies seems too old，new version of torchsparse requires pytorch over 1.9.0.I updated my environment according to #145 and solved AssertionError according to #109.
  
However ,when i run `python tools/tsdf_fusion/generate_gt.py`,such error comes out:

`RuntimeError:module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .`

**Comment by shaform** [comment]
@Cyberyyc Hello, how did you solve the problem?
