### ISSUE TITLE
camera poses format?

### ISSUE THREAD

**Issue by masterchop** [zju3dv/NeuralRecon#17]
What is the format for the camera poses?
I dont have an iphone but i can get Position,velocity,acceleration,rotation for the video feed, what order or format i need to set them to pass them to this model?

**Comment by JiamingSuen** [comment]
Please refer to [this data processing script](https://github.com/zju3dv/NeuralRecon/blob/master/tools/process_arkit_data.py)

**Comment by masterchop** [comment]
i took alook and i can see that is using a txt file: ARposes.txt
which is great, i can generate one but what is the format of that file i cant find it in the repo.

**Comment by JiamingSuen** [comment]
You may refer to the [example data](https://drive.google.com/file/d/1i7yDY-oautHgwrDPUrB7BuZytiIYhxfY/view?usp=sharing), which is provided in DEMO.md.
