### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by jeffin07** [zju3dv/NeuralRecon#22]
Hi,
First of all great work. I would like to know if  I want to test this method using my own dataset, say  I have a small video and u want to try it out what are the steps that I need to follow before I run the inference. I found that you follow the scannet data structure, so can you tell me the steps for converting a custom dataset that will be able to run this method

**Comment by JiamingSuen** [comment]
https://github.com/zju3dv/NeuralRecon/blob/master/DEMO.md

**Comment by jeffin07** [comment]
@JiamingSuen Thank you for the reply. So in order to run with custom data, it requires an iOS environment. Is that correct ?  Is there a way if we can run it using a custom dataset without iOS, like can we convert a video into Scannet structure ?

**Comment by JiamingSuen** [comment]
Yes, an iOS device is required. Similar to [this reply](https://github.com/zju3dv/NeuralRecon/issues/16#issuecomment-852818378), NeuralRecon requires camera poses with metric scale as input.
