### ISSUE TITLE
memory leak during training 

### ISSUE THREAD

**Issue by hanamizukigakki** [zju3dv/NeuralRecon#24]
We followed the readme and tried the training process with the scannet dataset. We found an obvious memory leak that made it difficult to complete one epoch iteration. Are there any suggestions to help locate the problem?

**Comment by JiamingSuen** [comment]
I cannot reproduce this problem in our testing. Maybe we can further help you if you can provide more information, but generally a memory leaking problem is very hard to debug when it is not reproducible on other machines.

**Comment by hanamizukigakki** [comment]
We have debugged the code carefully and found that the problem should come from `self.tsdf_cashe` in `datasets/scannet.py`. It worked fine after removal.

**Comment by chinmay1148** [comment]
@hanamizukigakki  can you show the edited code. 

I am facing a runtime error, i think this might solve it 
RuntimeError: Too many open files. Communication with the workers is no longer possible. Please increase the limit using `ulimit -n` in the shell or change the sharing strategy by calling `torch.multiprocessing.set_sharing_strategy('file_system')` at the beginning of your code
