### ISSUE TITLE
Some questions about training requirement and convergence time

### ISSUE THREAD

**Issue by Radium98** [zju3dv/NeuralRecon#25]
Hi, friends, as much as I can see from the demo, your work is really great. But I have some questions that I want you to answer. The problem is that I don't have enough GPUs, all I have is a single RTX2080Ti or RTX3090, I really want to konw your training consumption both in graphic memory and time. Can I use 2080Ti to train your model even if it cost more time? And if RTX3090 supports your code ? Thank you very much , I 'll be glad to receive your earliest reply when you are not too busy.

**Comment by JiamingSuen** [comment]
We used 8x Tesla V100 for training, and the training converges at 47 epochs, which takes ~31h. Using a single 2080Ti or 3090 would be possible, but it will take a much longer time.

**Comment by Radium98** [comment]
Thank you for your reply. But I still have a doubt that when I read your code, your experiment configuration is `export CUDA_VISIBLE_DEVICES=0,1`. It seems that 2×V100 is enough for graphic memory. Have you tried to train the network using only 2× V100？

**Comment by JiamingSuen** [comment]
We use data-parallel in the training, which means that multiple GPUs are used to speed up the overall training time, instead of trying to fit one batch of data into the memory of multiple GPUs (i.e., model-parallel). It is possible to use two V100 for training, but it will take a longer time.

**Comment by Radium98** [comment]
Thank you very much, I will think about my training strategy carefully. If I have other doubts, I 'll set up issues again.

**Comment by ZuoJiaxing** [comment]
@Radium98  Did you find the proper training strategy? I got a similar problem as you.
