### ISSUE TITLE
question about meta data generation part

### ISSUE THREAD

**Issue by HeCraneChen** [zju3dv/NeuralRecon#26]
Thanks for releasing this! For CPU version or generate_gt, it seems that, when using generate_gt.py to obtain tsdf, you commented color_all on line 224, that leads to color_all in save_tsdf_full to be empty, then color_im is empty. The code will report the following error. Is there a particular reason to comment line 224? I tried to uncomment this and use color info, but still weren't able to figure  things out. It seems to me that, the color_im has been flattened into one channel previously, is it a typo that new_color = color_im[pix_y[valid_pts], pix_x[valid_pts]] use two indices to access color_im? Thanks!

Traceback (most recent call last):
  File "tools/tsdf_fusion/generate_gt.py", line 289, in <module>
    process_with_single_worker(args, files[w_idx])
  File "tools/tsdf_fusion/generate_gt.py", line 230, in process_with_single_worker
    save_tsdf_full(args, scene, cam_intr, depth_all, cam_pose_all, color_all, save_mesh=False)
  File "tools/tsdf_fusion/generate_gt.py", line 95, in save_tsdf_full
    tsdf_vol_list[l].integrate(color_image, depth_im, cam_intr, cam_pose, obs_weight=1.)
  File "./tools/tsdf_fusion/fusion.py", line 298, in integrate
    new_color = color_im[pix_y[valid_pts], pix_x[valid_pts]]
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

**Comment by JiamingSuen** [comment]
As discussed with Pengfei, we recommend using a GPU-enabled machine for data preprocessing and training. Feel free to reopen this issue if you have further questions.

**Comment by HeCraneChen** [comment]
Thanks Jiaming. I'll try either to use GPU version, or try to fix the CPU version and submit a pull request.

**Comment by Jingjinganhao** [comment]
> Thanks Jiaming. I'll try either to use GPU version, or try to fix the CPU version and submit a pull request.
Thanks for releasing this! I want to run the demo on CPU. Is the CPU version available？
