### ISSUE TITLE
question about using our own data

### ISSUE THREAD

**Issue by JasonYinn** [zju3dv/NeuralRecon#28]
Thank you for this wonderful work! I am trying to apply this model on our own data captured from Android devices, but I cannot align our coordinate system to that of ScanNet, could you please provide any advice ?

**Comment by JiamingSuen** [comment]
You may align the coordinate system of ARCore (or other VI-SLAM systems on Android) to ScanNet by doing something like [this](https://github.com/zju3dv/NeuralRecon/blob/master/tools/process_arkit_data.py#L83).

**Comment by JasonYinn** [comment]
Thank you for your reply, problem just solved today~

**Comment by lihui1998** [comment]
> Thank you for your reply, problem just solved today~
hello, Can we discuss some questions about how to get data through arcore.

**Comment by linzhenyuyuchen** [comment]
> Thank you for your reply, problem just solved today~

I met the same problem as you.
Could you please provide your solution of applying this wonderful model to your own data.

**Comment by Haonan-DONG** [comment]
> > Thank you for your reply, problem just solved today~
> 
> I met the same problem as you. Could you please provide your solution of applying this wonderful model to your own data.

My solution is also to align my own data (RGB-D sequence) with the Scannet datasets by transforming the camera pose with proper rotation and translation. However, my solution is cumbersome, where the transformation matrix (rotation, translation) is manually adjusted by comparing the fused point cloud of our data with the fused point cloud of Scannet. 

So, it might work with the following two points:
1. the fused point cloud is located on the X-Y plane as [here](https://github.com/zju3dv/NeuralRecon/blob/master/tools/process_arkit_data.py#L83).
2. The normal vector of the ground should be parallel to the Z-axis and facing the positive direction of the Z-axis.

You can check the result of our data at [here](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/tree/main/indoor_reconstrucion) and the testing data will be released soon.

**Comment by laiba12345** [comment]
> Thank you for your reply, problem just solved today~

I really need help with this. How did you convert left handed coordinates to scannet coordinates?
