### ISSUE TITLE
Depth fusion vs RGBD fusion when generating GT

### ISSUE THREAD

**Issue by HeCraneChen** [zju3dv/NeuralRecon#29]
One quick question. When generating GT, my guess is you ended up using just depth fusion instead of RGBD fusion? Did I understand it correctly? Is this because experimentally, this way works better?

**Comment by JiamingSuen** [comment]
I don't quite understand the difference between the “depth fusion” and the “RGB-D fusion” in your context, it seems as the same fusion technique to me. Would you please elaborate more?

If you are referring to the “RGB” part, NeuralRecon doesn't predict the color of the reconstruction, and thus no color GT is required.

**Comment by HeCraneChen** [comment]
Thanks for the quick response. That answers my question. I was mainly wondering if it makes sense if I comment everything related to RGB when generating the TSDF GT in CPU version. If you say so, it's probably fine.
