### ISSUE TITLE
Runnable on Windows?

### ISSUE THREAD

**Issue by bycloudai** [zju3dv/NeuralRecon#3]
Hi, the work you guys have look amazing!

As the documentation is pretty long and have quite a lot of steps to get it running, I just want to double check if this would be possible to run on a Windows machine or not. Please let me know if it's possible.

Also, sorry to bother you guys with such trivial matter! And thanks in advance

**Comment by JiamingSuen** [comment]
Thanks for your interest in our work!

Unfortunately, we don't support Windows for now. The major reason is that our major dependency, [`torchsparse`](https://github.com/mit-han-lab/torchsparse), is not supporting Windows. You can find more info about it [here](https://github.com/mit-han-lab/torchsparse/issues/12). Adapting the framework to Windows is potentially possible but it will involve a lot of additional work. We recommend you install Ubuntu 18.04+ to run NeuralRecon.

Feel free to reopen this issue if you have more questions.
