### ISSUE TITLE
Error in BatchNorm operation during training

### ISSUE THREAD

**Issue by louzq16** [zju3dv/NeuralRecon#30]
![neuralrecon_issue](https://user-images.githubusercontent.com/44044820/125784767-412aaaaa-d21b-4d72-921d-d076c12b9d9f.png)
Thank for your great work! I occasionally met some problems during training the NeuralRecon. As shown in the Fig, error occurs in batchnorm operation since the input channal is 1. How to fix that problem?

**Comment by JiamingSuen** [comment]
Unfortunately, I (and many others) can't reproduce this error on our side. More information is needed to determine the problem.

**Comment by louzq16** [comment]
Thank for your reply. In fact, in following re-training process, I never met such error again.....
