### ISSUE TITLE
about TagBA.

### ISSUE THREAD

**Issue by Techhooli** [zju3dv/NeuralRecon#31]
Thanks for your excellent work. Can you tell me some information about TagBA. It's one developed AI SDK? or open-source dataset? I try to search for some contents on the google. But I dont know what it is.

**Comment by JiamingSuen** [comment]
TagBA is an internal system that doing BA with AprilTags. It's an alternative for ARKit to obtain camera poses with metric scales. You may refer to [this paper](https://arxiv.org/abs/1910.00679) for more information.
