### ISSUE TITLE
Question about the choice of maximum depth

### ISSUE THREAD

**Issue by xjiangan** [zju3dv/NeuralRecon#32]
Thank you for your great work.
I have a little question about the choice of the maximum depth. The default value is 3m and I am wondering is there any specific reason for this. Can we increase the configuration of maximum depth and number of voxels so that NeuralRecon can support larger depth such as 5m? Is there any experiment results with different choice of maximum depth?

**Comment by JiamingSuen** [comment]
We empirically chose 3m because most scenes on ScanNet is within this range. Using a larger depth range would be possible but we haven't tried it before. The motion parallax may not be enough for the far-away scenes.

**Comment by xjiangan** [comment]
Thank you for your reply. I will have a try.
