### ISSUE TITLE
Camera intrinsic parameters from ARKit data logger.

### ISSUE THREAD

**Issue by PyojinKim** [zju3dv/NeuralRecon#39]
Hi,

First of all, I am a big fan of this project, and I really appreciate opening your source code publicly.

It seems like the demo.py with ARKit data utilizes the camera intrinsic matrix (K) from the "Frames.txt" directly.
I am just curious about how accurate the camera intrinsic parameters are from the iPhone compared to the manual camera calibration with checkerboard?
Did you compare the camera intrinsic matrix K from the "Frames.txt" vs. manual camera calibration with the checkerboard??
I think inaccurate camera intrinsic matrix K can severely degrade the performance of NeuralRecon....??

Thanks,
Pyojin Kim.

**Comment by JiamingSuen** [comment]
1. The intrinsics in Frames.txt are directly from ARKit and I haven't check their accuracy.
2. Yes, inaccurate intrinsics can definitely degrade the performance of NeuralRecon, and you are more than welcome to check if the performance can be further improved with better camera calibrations (intrinsics and extrinsics).

**Comment by PyojinKim** [comment]
> 1. The intrinsics in Frames.txt are directly from ARKit and I haven't check their accuracy.
> 2. Yes, inaccurate intrinsics can definitely degrade the performance of NeuralRecon, and you are more than welcome to check if the performance can be further improved with better camera calibrations (intrinsics and extrinsics).

I will do the manual calibration with the checkerboard, and share the 3D reconstruction results in this issue within this week.

**Comment by PyojinKim** [comment]
![comparsion](https://user-images.githubusercontent.com/19288158/128684341-8f2e2365-064f-42eb-9046-0362073ed3e2.png)

The top one is the result with the camera intrinsic from iPhone API, and the bottom one is the result with the manual camera calibration on the MATLAB toolbox.
The camera intrinsic matrix K from iPhone API (iPhone XS is used) is quite accurate and similar compared to the manual calibration K result with checkerboard.
So, I think the camera intrinsic K matrix from ios_logger is good and accurate enough to perform the NeuralRecon.. :)

I will close this issue.
