### ISSUE TITLE
ios_logger_process.py

### ISSUE THREAD

**Issue by cdcseacave** [zju3dv/NeuralRecon#4]
Thank you for such a well documented source code. Can you pls share also `ios_logger_process.py`?

**Comment by JiamingSuen** [comment]
This file is renamed to [`process_arkit_data.py`](https://github.com/zju3dv/NeuralRecon/blob/master/tools/process_arkit_data.py) before the release and the path in `DEMO.md` was not updated accordingly. Thanks for pointing it out and sorry for the confusion.

**Comment by cdcseacave** [comment]
thank you
