### ISSUE TITLE
no valid points: scale 0  when runing example data

### ISSUE THREAD

**Issue by achao2013** [zju3dv/NeuralRecon#40]
the following is the detailed error infos, i search the similar issues and find #6 , but i check the code  and the X-Y plane in the ARKit coordinates has be moved downwards a little  in tools/process_arkit_data.py(cam_pose_dict[id][2, 3] += 1.5). 
so i wonder to know what's wrong with it?

@JiamingSuen

2021-08-07 10:21:25.395 | INFO     | __main__:<module>:32 - First run on this captured data, start the pre-processing...
Extract images from video...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5301/5301 [00:39<00:00, 135.46it/s]
Load intrinsics and extrinsics
Processing camera intrinsics...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 5301/5301 [00:00<00:00, 367765.61it/s]
data source: ARKit
Saving camera extrinsics...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 5301/5301 [00:00<00:00, 7865.03it/s]
Saving camera intrinsics...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 5301/5301 [00:00<00:00, 8375.12it/s]
Keyframes selection...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 5301/5301 [00:00<00:00, 37386.61it/s]
Saving fragments file...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<00:00, 148830.14it/s]
2021-08-07 10:22:06.263 | INFO     | __main__:<module>:37 - Running NeuralRecon...
2021-08-07 10:22:06.265 | INFO     | __main__:<module>:50 - Initializing the model on GPU...
2021-08-07 10:22:07.920 | INFO     | __main__:<module>:58 - Resuming from ./checkpoints/release/model_000047.ckpt
2021-08-07 10:22:08.043 | INFO     | __main__:<module>:64 - Start inference..
  0%|                                                                                                                                                 | 0/110 [00:00<?, ?it/s]/home/achao/3d/debug-NeuralRecon/NeuralRecon/ops/back_project.py:29: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  batch_ind = torch.nonzero(coords[:, 0] == batch).squeeze(1)
2021-08-07 10:22:08.267 | WARNING  | models.neucon_network:forward:184 - no valid points: scale 0
  0%|                                                                                                                                                 | 0/110 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 89, in <module>
    save_mesh_scene.save_incremental(epoch_idx, 0, sample['imgs'][0], outputs)
  File "/home/achao/3d/debug-NeuralRecon/NeuralRecon/utils.py", line 256, in save_incremental
    tsdf_volume = outputs['scene_tsdf'][batch_idx].data.cpu().numpy()
KeyError: 'scene_tsdf'

**Comment by JiamingSuen** [comment]
This should be a resolved issue. Please make sure that you are using the latest commit.

**Comment by achao2013** [comment]
> This should be a resolved issue. Please make sure that you are using the latest commit.

i  confirm the commit repeatly.  The git log shows:

commit 92a6d123d23ef9888dd6ebb6307b3b98a7ae809c
Author: Jiaming Sun <suenjiaming@gmail.com>
Date:   Sun Jul 4 21:36:54 2021 +0800

    Update README.md

**Comment by achao2013** [comment]
can you help me to check this problem again? It is easy and quick to pull the code and run the demo again.
I git clone the newest code, and  download the example data named neucon_demodata_b5f1,  get the model model_000047.ckpt , set SAVE_INCREMENTAL: True in demo.yaml.

I think there are some  new commit for other problem which  let this problem  appear again. 
@JiamingSuen

**Comment by Burningdust21** [comment]
> can you help me to check this problem again? It is easy and quick to pull the code and run the demo again.
> I git clone the newest code, and download the example data named neucon_demodata_b5f1, get the model model_000047.ckpt , set SAVE_INCREMENTAL: True in demo.yaml.
> 
> I think there are some new commit for other problem which let this problem appear again.
> @JiamingSuen

Hi, we successfully run reconstruction on demo data with latest code and set 'SAVE_INCREMENTAL' to be Ture, no sign of any error.

The warning 'no valid points: scale 0' indicates reconstruction has failed, which causing Key 'scene_tsdf' to be missing. You can check whether there's any parameter being modified.

**Comment by JiamingSuen** [comment]
@achao2013 Please make sure that you have complete the environment configuration and are using an unmodified version of the code.

**Comment by achao2013** [comment]
thanks. I find the reason. It's caused by  cuda version and  the correspond python dependent libraries.

**Comment by Cli98** [comment]
@achao2013 Could you tell me what's the root cause for this? I run into same issues.
Can you tell me the exact version you use to fix this issue? And what's the version that failed?
