### ISSUE TITLE
ScanNet data

### ISSUE THREAD

**Issue by Innocence4822** [zju3dv/NeuralRecon#41]
I'd like to ask about scannetv2_ test.txt，scannetv2_ train.txt，scannetv2_ Val.txt, how do I get these three files

**Comment by JiamingSuen** [comment]
You can obtain the train/val/test split information from [here](https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark). I've also included this information in the README. Thanks for the heads up.
