### ISSUE TITLE
Apply to new datasets

### ISSUE THREAD

**Issue by hyunJIN7** [zju3dv/NeuralRecon#42]
Hi,

Thank you for the great work.

I try to apply demo.py on TUM datasets and EuRoc(drone) datasets. But I didn’t get an accurate result.

<img width="856" alt="rgb_3_teddy" src="https://user-images.githubusercontent.com/35680342/129817353-f729fcce-2c22-412f-b04a-008c288e8411.PNG">
<img width="841" alt="v2_0_easy" src="https://user-images.githubusercontent.com/35680342/129817381-cd3bf226-4836-4180-ae93-6d87e101257e.PNG">

The first picture is the result of applying the TUM dataset picture, and the second image is the result of using EuRoc data.

Is it correct that the results are like this?
Have you applied the NeuralRecon code to the datasets mentioned?

Thanks,
Hyunjin Kim.

**Comment by JiamingSuen** [comment]
We haven't tested NeuralRecon on TUM and EuRoC datasets. Please make sure that the camera pose format is correctly converted, and the z-axis of the poses are shift according to:
https://github.com/zju3dv/NeuralRecon/blob/master/tools/process_arkit_data.py#L83

**Comment by imbinwang** [comment]
Hi @hyunJIN7, have you solved the problem?

**Comment by hyunJIN7** [comment]
Hi.
I haven't been able to solve this problem yet.

**Comment by neuhsm** [comment]
https://github.com/zju3dv/NeuralRecon/issues/76#issuecomment-1059915310
could you please give the result on 7-scenes or how to process the pose ,in fact, i have tried it on several datasets,some need to add a 1.5 ,some need to rot the x-axis like process the demo data in ARkit , but all of the result seems worse than your demo data ,the demo result is all right,so i think my operate is right, the problem in processing the pose seems with the biggest probability。（i'm not very good at english,and i'm new in 3D Reconstruction,so Please forgive my question may not be standardized）
here are some results in other datasets
first ,the demo data provided by the author
![9K5XMZ{QO1G_B3L6WLJ`W K](https://user-images.githubusercontent.com/76637172/156915161-38f4c8a8-f931-47ea-a386-6c266dd44c15.png)

the TUM dateset
![C(X)_VE4$SX$YH6Q121Y)JI](https://user-images.githubusercontent.com/76637172/156915183-854bf85d-cca6-452f-92f2-d71a31a86f80.png)

the scannet data(i'm not able to download the full scannet,so it's 100 times downsampled,it seems will be ok if use more photos)
![)8(GK$(0{O4_EI(_D2PT9YR](https://user-images.githubusercontent.com/76637172/156915154-1ae6098a-0951-4f50-a074-873804b3270d.png)
the 7-scenes dataset
![@GVK66@0%I~LFK3YR{BWYYD](https://user-images.githubusercontent.com/76637172/156915233-841a33b3-00f8-4a9d-a03c-233363810837.png)
finally,i use my phone get a video ,and use the orb-slam2 to get the pose of key-frame(i can't use a iphone to use ARkit)
![PJI{71I1AC)OGZ5$}01SI7N](https://user-images.githubusercontent.com/76637172/156915299-c1422aa3-752d-4200-bb44-ebb092b461ab.png)
