### ISSUE TITLE
Program running error

### ISSUE THREAD

**Issue by Innocence4822** [zju3dv/NeuralRecon#43]
Why do I run the command ：python main.py --cfg ./config/test.yaml
and the following results appear：
number of gpus: 1
creating log file ./checkpoints/20210822_203302_test.log

 but the program doesn't run down

**Comment by JiamingSuen** [comment]
We cannot determine the problem with the given information. Please make sure that the dependencies (mainly torchsparse) is fully compiled and correctly installed.

**Comment by daowanpeng** [comment]
> We cannot determine the problem with the given information. Please make sure that the dependencies (mainly torchsparse) is fully compiled and correctly installed.




> 

I had the same problem as you described，have you solved this yet? Moreover, I find that in the main.py the test() function, there is an infinite loop because of the "while True: "
