### ISSUE TITLE
ARKit evaluation

### ISSUE THREAD

**Issue by hyunJIN7** [zju3dv/NeuralRecon#44]
Hi,
I am a big fan of this project.

I want to evaluation ARKit Reconstruction results.
So I'm trying to apply the evaluation.py code to ARKit Recon results.
For that, I need a depth map of ARKit Recon results.

NeuralRecon paper says that "we render the reconstructed mesh to
the image plane and obtain depth map estimations.". 
So I trued to find the code to get the depth map from the reconstructed mesh result, but I couldn't find it. Could you tell me what the code for estimating the depth map from the reconstructed mesh ?

Thanks,
Hyunjin Kim.

**Comment by JiamingSuen** [comment]
Hi @hyunJIN7, if the goal is to evaluate ARKit reconstructions, you will need a ground truth reconstruction, which can be obtained from reconstruction software with depth sensors (e.g. LiDAR on the iPad Pro, with [3D Scanner App](https://www.3dscannerapp.com/)). 

For the depth map rendering code, you can refer to [this file](https://github.com/zju3dv/NeuralRecon/blob/5d2a474f3829562b2bc11482d14df3468610285d/tools/evaluation.py#L137) for further details.

**Comment by hyunJIN7** [comment]
Thank you for your answer. 
I will try again after getting gt data with 3D Scanner.
