### ISSUE TITLE
Mesh Texturing

### ISSUE THREAD

**Issue by danglu999** [zju3dv/NeuralRecon#45]
NeuralRecon does not produce colored mesh. You may use a texture mapping tool like [this](https://github.com/nmoehrle/mvs-texturing) to apply image texture to the reconstructed mesh. 
_Originally posted by @JiamingSuen in https://github.com/zju3dv/NeuralRecon/issues/27#issuecomment-874031869_

Hi, thanks a lot for your work!
As you mentioned, I tried to use the tool (mvs-texturing) for mapping image texture to a reconstructed mesh. The tool requires the distortion coefficients as inputs, would you please give me a guide how should I get the distortion coefficients?

**Comment by HtForBetterLife** [comment]
> 

hello, did you solve the problem? How should I use that tool, please give me some steps. Thanks!

**Comment by danglu999** [comment]
just fill in 0 for distortion coefficients
