### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by toyato** [zju3dv/NeuralRecon#49]
Because my gpu memory is too small, when I run demo.py I get the following error
`RuntimeError: CUDA out of memory. Tried to allocate 666.00 MiB (GPU 0; 2.00 GiB total capacity; 557.62 MiB already allocated; 549.02 MiB free; 662.00 MiB reserved in total by PyTorch)`
How do I modify the code so that it can run on 2G memory, thanks!

**Comment by JiamingSuen** [comment]
It will require a change in voxel sizes in order to fit 2GB GPU memory, which means that you will have to train the network from scratch.
