### ISSUE TITLE
dead code?

### ISSUE THREAD

**Issue by cdcseacave** [zju3dv/NeuralRecon#5]
here you modify the pose, but if I'm not mistaken (I'm a python noob), you finally use the unmodified pose; is this intended?
https://github.com/zju3dv/NeuralRecon/blob/f7ae3b82369fc031708bc78f395377a424e1be82/tools/process_arkit_data.py#L87

**Comment by JiamingSuen** [comment]
The modified pose is unused and it does not affect the reconstruction. Originally we intended to shift the z-axis in the pose to match the ground plane level on ScanNet. We later found out it's actually not necessary. The code has been removed now, thanks for the heads up!

**Comment by JiamingSuen** [comment]
Feel free to reopen this issue if you have more questions.

**Comment by JiamingSuen** [comment]
As suggested in #6 and commit eec464fd63fd033cd0e9018842faad8dda6e1f83, it turns out to be necessary to shift the z-axis. Sorry for the confusion.
