### ISSUE TITLE
Lower iPhone camera position leads to bad result

### ISSUE THREAD

**Issue by wtiandong** [zju3dv/NeuralRecon#52]
Hi,
Thanks for your great work!
I have a problem that when I attach my iPhone to my tool car (remote control), which the height of iPhone camera position is 5 cm with respect to the ground, neural recon gives me a bad result. But if I hold my iPhone in hand (height is 1.5m) and sample the same place, the result is great. Do I need to modify something in data preprocessing or something else? 
Thank you!

**Comment by JiamingSuen** [comment]
5cm to the ground is too far away from the poses in the training data. You will have to train the network with similar data in order to make it work.
