### ISSUE TITLE
RTX 30系列显卡是否支持

### ISSUE THREAD

**Issue by cucdengjunli** [zju3dv/NeuralRecon#55]
您好 我是中国传媒大学研究生，正在学习您的工程，您的cuda要求为10.2， 请问能否换为cuda11 ，因为RTX30系列显卡不支持cuda10.2

**Comment by JiamingSuen** [comment]
It should be compatible with CUDA 11 but I've not tested it. Please submit a issue to the `torchsparse` repo if you met any problem with CUDA 11.

**Comment by danglu999** [comment]
Hi, @cucdengjunli 
I have tested it on RTX 3060 and 3070, they both work well

**Comment by cucdengjunli** [comment]
> Hi, @cucdengjunli 
> I have tested it on RTX 3060 and 3070, they both work well

torchsparch is not work well

**Comment by HaFred** [comment]
A PyTorch environment with matched version setup will solve the problem.
