### ISSUE TITLE
texture mapping on your output.ply

### ISSUE THREAD

**Issue by cucdengjunli** [zju3dv/NeuralRecon#59]
![Screenshot_20211010_145346.jpg](https://user-images.githubusercontent.com/46188762/136685903-4f5e3d51-f298-48e3-b901-722f0905fa26.jpg)

![Screenshot_20211010_145316.jpg](https://user-images.githubusercontent.com/46188762/136685908-19c80e9d-b379-4fa5-9b98-64019910350a.jpg)

could you please tell me, how do you generate this textures on your gray output.ply file.  Like this two example you offered.
And how do you build your AR demo?
On own data captured by iphone.

**Comment by cucdengjunli** [comment]
https://github.com/nmoehrle/mvs-texturing/issues/180

This is a similar question

**Comment by cucdengjunli** [comment]
> ![Screenshot_20211010_145346.jpg](https://user-images.githubusercontent.com/46188762/136685903-4f5e3d51-f298-48e3-b901-722f0905fa26.jpg)
> 
> ![Screenshot_20211010_145316.jpg](https://user-images.githubusercontent.com/46188762/136685908-19c80e9d-b379-4fa5-9b98-64019910350a.jpg)
> 
> could you please tell me, how do you generate this textures on your gray output.ply file.  Like this two example you offered.
> On own data captured by iphone.
> 
> 
> 
> 

😢how do you build your AR demo?

**Comment by ShiqiMa** [comment]
@JiamingSuen Hi, could you please clarify the pipeline of using the mvs-texturing tool to map texture. Because with the result .ply file, it seems that I cannot execute the ./texrecon by mvs-texturing. In this case, what else should I do?
