### ISSUE TITLE
Real-Time Reconstrution display question

### ISSUE THREAD

**Issue by Nekomiya-fubuki** [zju3dv/NeuralRecon#64]
Thank you very much for providing the code, but I still have a question that I set both VIS_INCREMENTAL and SAVE_INCREMENTAL to True, but when running the demo, only the rgb image is displayed in real time, and step-by-step mesh reconstruction is  not displayed. Is it because my operation is wrong or do I need to write a mesh synchronization visualization program？

**Comment by JiamingSuen** [comment]
Please make sure Open3D is correctly installed and your environment is supporting rendering with OpenGL.

**Comment by Fupeng-Chu** [comment]
> Thank you very much for providing the code, but I still have a question that I set both VIS_INCREMENTAL and SAVE_INCREMENTAL to True, but when running the demo, only the rgb image is displayed in real time, and step-by-step mesh reconstruction is not displayed. Is it because my operation is wrong or do I need to write a mesh synchronization visualization program？

Hi, I have encountered the same problem. Have you solved it?
