### ISSUE TITLE
Generalization

### ISSUE THREAD

**Issue by cdcseacave** [zju3dv/NeuralRecon#7]
I managed to reproduce the paper result on the demo dataset with the code and trained network published here, and the result look great. However when trying it on custom datasets I do not get good results, no matter what scene type I try (indoor, outdoor, office like scene, etc); here is one example, one of the best results I got this far:
![image](https://user-images.githubusercontent.com/2802670/118683969-7d853e00-b80a-11eb-975c-bafe75ef831d.png)

Do you think I am doing something wrong at passing the camera extrinsics I get from ARKit or it is known that the method does not generalize well and performs well only on the trained data?

I used a custom acquisition method and a relatively large baseline between consecutive images (~1 image/s). Should I try a much higher FPS?

**Comment by JiamingSuen** [comment]
> I used a custom acquisition method and a relatively large baseline between consecutive images (~1 image/s). Should I try a much higher FPS?

I believe your custom keyframe selection strategy is the major reason for the poor result. As a learning-based approach, NeuralRecon assumed that the range of baseline used during inference is similar to the range used at the training time.

> it is known that the method does not generalize well and performs well only on the trained data?

Please note that the provided demo dataset is **not** used for training, and the data domain is quite different from the training dataset (ScanNet). During our testing, NeuralRecon generalizes reasonably well to the type of scenes you mentioned (indoor, outdoor, office-like scene, etc) when the recommended keyframe selection strategy is followed (i.e., using the provided data processing scripts to select keyframes).

**Comment by cdcseacave** [comment]
Thank you, that is helpful, I will redo my experiments.

**Comment by JiamingSuen** [comment]
Feel free to reopen this issue if you want to discuss your new experimental results😃.
