### ISSUE TITLE
Why do we need to rotate the x axis for 180 degrees for ARKit data?

### ISSUE THREAD

**Issue by HaFred** [zju3dv/NeuralRecon#75]
In the following line, the rotation matrix comes from ARKit data needs to rotate for 180 degrees
https://github.com/zju3dv/NeuralRecon/blob/cd047e2356f68f60adfb923f33572d712f64b57a/tools/kp_reproject.py#L52
before rotating 90 degrees for changing Y-up  in ARKit into Z-up as in 
https://github.com/zju3dv/NeuralRecon/blob/cd047e2356f68f60adfb923f33572d712f64b57a/tools/kp_reproject.py#L57

Hi @JiamingSuen , may I know why is this needed for line 52? I did try to comment out this line but turns out the inference result is no longer meaningful. But I don't get the reason behind this. Maybe you can enlighten me a little bit, thank you.

**Comment by HaFred** [comment]
Correct me if I am wrong, I guess with line 52, it just flips the Y-axis 180 degrees to fit it in the target volume space.

**Comment by neuhsm** [comment]
i have some other thoughts,[https://github.com/magicleap/Atlas/issues/34#issuecomment-876406864](url)
here means that arkit with the y-up while here[https://github.com/magicleap/Atlas/issues/7#issuecomment-682180132](url) say normal axis with y-down,so i think line 52 used to make to fit the normal camera axis, then rotate x-axis to find the space can work, one thing maybe important,line52 is a right multiply while rotx function is left multiply,they have different usages .
but i'm not very sure how the line52 works in math or physics,the rotx have very clear meaning,if you know this ,please tell me.

**Comment by neuhsm** [comment]
oh ,i find some information on internet ,Coordinate have 2 standards ，one called photo grammetry, the other called cv,the arkit is photo grammetry,and in line52,it just adjust  photogrammetry to cv, if you can read chinese ,you can look at this [https://blog.csdn.net/u012348774/article/details/68946571?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_title~default-0.pc_relevant_antiscanv2&spm=1001.2101.3001.4242.1&utm_relevant_index=3](url).of course you may find some about this in your way.
