### ISSUE TITLE
A typo in neucon_network？

### ISSUE THREAD

**Issue by HaFred** [zju3dv/NeuralRecon#87]
https://github.com/zju3dv/NeuralRecon/blob/cd047e2356f68f60adfb923f33572d712f64b57a/models/neucon_network.py#L161
Hi @JiamingSuen , I was trying to train NeuralRecon from scratch but failed to reach the performance mentioned in the paper.
After some investigation, I found out something I could not comprehend here in this line. Is it a typo for the scale argument? Should it be `scale` rather than `i` for this argument? Thank you very much.

**Comment by Rock-100** [comment]
@HaFred Hello HaFred, I also cannot get the performance mentioned in the paper. Have you solved this problem? Many thanks.
